_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  # WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_101_C4_3x/138204752/model_final_298dad.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN: 
    HEAD_NAME: "StandardRPNHead"
  ROI_HEADS:
    NUM_CLASSES: 1
    NAME: "Res5ROIHeads"
  PIXEL_MEAN: [98.13131, 98.13131, 98.13131]
  PIXEL_STD: [0.57541465, 0.57798347, 0.56536374]
INPUT:
  MIN_SIZE_TRAIN: (500,) # set 1000 to compare, keep trian and test the same
  MIN_SIZE_TEST: 500
  RANDOM_FLIP: "none"
  CROP:
    ENABLED: False # only using resize to keep the same size when train and test
    TYPE: "relative"
    SIZE: [0.5, 0.5]
DATASETS:
  TRAIN: ('sar_ship_train',)
  TEST: ('sar_ship_test',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (400, 500)
  MAX_ITER: 600  # 17.4 epochs
  WARMUP_ITERS: 50
  CHECKPOINT_PERIOD: 100
TEST:
  EVAL_PERIOD: 50