_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN: 
    HEAD_NAME: "StandardRPNHead"
  ROI_HEADS:
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 256
    NAME: "Res5ROIHeads"
  PIXEL_MEAN: [78.11523, 78.11523, 78.11523]
  PIXEL_STD: [0.53109455, 0.53346551, 0.52181779]
INPUT:
  MIN_SIZE_TRAIN: (500,) # set 1000 to compare, keep trian and test the same
  MIN_SIZE_TEST: 500
  RANDOM_FLIP: "none"
  CROP:
    ENABLED: False # only using resize to keep the same size when train and test
    TYPE: "relative"
    SIZE: [0.5, 0.5]
DATASETS:
  TRAIN: ('sar_ship_train',)
  TEST: ('sar_ship_test',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (600, 800)
  MAX_ITER: 900  # 17.4 epochs
  WARMUP_ITERS: 5
  CHECKPOINT_PERIOD: 100
TEST:
  EVAL_PERIOD: 100